version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - project-network
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  salon-be:
    container_name: salon-be
    build:
      context: .
      dockerfile: salon-be.Dockerfile
      args:
        GITHUB_TOKEN: "${GITHUB_TOKEN}"
        REPO_URL: "${REPO_URL}"
    ports:
      - 2888:2888
      - 50051:50051
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - REPO_URL=${REPO_URL}
    volumes:
      - ./dev.env:/usr/src/app/.env # Updated path to match WORKDIR in Dockerfile
    networks:
      - project-network
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:

networks:
  project-network:
    name: project-network
    driver: bridge
